apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ei6doge3n-java-springboot
  janus-idp.io/tekton: ei6doge3n-java-springboot
  backstage.io/kubernetes-id: ei6doge3n-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ei6doge3n-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
